#ifndef FUNOS_STATUS_WORDS_H
#define FUNOS_STATUS_WORDS_H

/* See GlobalPlatform, clause 11.1.3 "General Error Conditions". */
#define SW_SUCCESS									0x9000
#define SW_BYTES_REMAIN								0x6100
#define SW_ERROR_WRONG_LENGTH						0x6700
#define SW_ERROR_LOGICAL_CHANNEL					0x6881
#define SW_ERROR_SECURITY_STATUS_NOT_SATISFIED		0x6982
#define SW_ERROR_CONDITIONS_OF_USE_NOT_SATISFIED	0x6985
#define SW_ERROR_INCORRECT_P1P2						0x6A86
#define SW_ERROR_INVALID_INSTRUCTION_BYTE			0x6D00
#define SW_ERROR_INVALID_CLASS_BYTE					0x6E00
#define SW_ERROR_UNKNOW								0x6F00

#endif /* FUNOS_STATUS_WORDS_H */