#ifndef FUNOS_COMMON_H
#define FUNOS_COMMON_H

#include <stdint.h>

#define SEMAPHORES_MAX	(8)
#define QUANTUM			500

#define FUNOS_SW_QUEUE_IS_EMPTY				0x6400
#define FUNOS_SW_BAD_PROC_ID				0x6401
#define FUNOS_SW_BAD_QUEUE_ID				0x6402
#define FUNOS_SW_QUEUE_TABLE_IS_FULL		0x6403

#define FUNOS_SW_DEFERRING_CTRL_ERR			0x6404
#define FUNOS_SW_INCORRECT_PROC_STATE		0x6405
#define FUNOS_SW_PROCESS_TABLE_IS_FULL		0x6406
#define FUNOS_SW_FAILED_TO_CREATE_PROCESS	0x6407
#define FUNOS_SW_FAILED_TO_ALLOCATE_STACK	0x6408


#define FUNOS_SW_OK					0X9000

#if !defined(NULL)
#	define NULL ((void*)0)
#endif

#define TRUE	0xD1
#define FALSE	0xFA

#endif /* FUNOS_COMMON_H */